spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5433/task_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  threads:
    virtual:
      enabled: true
application:
  config:
    user-url: http://localhost:8080
server:
  port: 8081